eks cluster not created

diff --git a/.github/workflows/cd.yaml b/.github/workflows/cd.yaml
--- a/.github/workflows/cd.yaml
+++ b/.github/workflows/cd.yaml
@@ -10,7 +10,9 @@ env :
   AWS_REGION: us-east-1
   EKS_CLUSTER_NAME: e2ecicd-cluster
   ECR_REPOSITORY: calculator-app
-  
+  EKS_ROLE_ARN: ${{ secrets.EKS_ROLE_ARN }} # IAM role ARN for EKS
+  SUBNET_IDS: ${{ secrets.SUBNET_IDS }}      # comma-separated subnet IDs
+  SECURITY_GROUP_IDS: ${{ secrets.SECURITY_GROUP_IDS }} # comma-separated SG IDs
 jobs:
   build-and-push:
       runs-on : ubuntu-latest
@@ -74,19 +76,39 @@ jobs:
 
        - name: Ensure EKS cluster exists
          run: |
-          if ! aws eks describe-cluster --name $EKS_CLUSTER_NAME --region $AWS_REGION &> /dev/null; then
-            echo "Cluster $EKS_CLUSTER_NAME not found. Creating..."
-            aws eks create-cluster \
-              --name $EKS_CLUSTER_NAME \
-              --region $AWS_REGION \
-              --kubernetes-version 1.29 \
-              
-              
-            echo "Waiting for cluster to become ACTIVE..."
-            aws eks wait cluster-active --name $EKS_CLUSTER_NAME --region $AWS_REGION
+          # Get default VPC ID
+           DEFAULT_VPC_ID=$(aws ec2 describe-vpcs \
+          --filters "Name=isDefault,Values=true" \
+          --query "Vpcs[0].VpcId" --output text --region $AWS_REGION)
+
+          SUBNET_IDS=$(aws ec2 describe-subnets \
+          --filters "Name=vpc-id,Values=$DEFAULT_VPC_ID" \
+          --query "Subnets[].SubnetId" --output text --region $AWS_REGION | tr ' ' ',')
+
+  
+           SECURITY_GROUP_IDS=$(aws ec2 describe-security-groups \
+          --filters "Name=vpc-id,Values=$DEFAULT_VPC_ID" \
+          --query "SecurityGroups[0].GroupId" --output text --region $AWS_REGION)
+
+ 
+           if ! aws eks describe-cluster --name $EKS_CLUSTER_NAME --region $AWS_REGION &> /dev/null; then
+           echo "Cluster $EKS_CLUSTER_NAME not found. Creating..."
+
+           aws eks create-cluster \
+           --name $EKS_CLUSTER_NAME \
+           --region $AWS_REGION \
+           --kubernetes-version 1.29 \
+           --role-arn $EKS_ROLE_ARN \
+           --resources-vpc-config subnetIds=$SUBNET_IDS,securityGroupIds=$SECURITY_GROUP_IDS
+
+          echo "Waiting for cluster to become ACTIVE..."
+          aws eks wait cluster-active --name $EKS_CLUSTER_NAME --region $AWS_REGION
+
+          echo "Cluster $EKS_CLUSTER_NAME is now ACTIVE."
           else
-            echo "Cluster $EKS_CLUSTER_NAME already exists."
+           echo "Cluster $EKS_CLUSTER_NAME already exists."
           fi
+
 
        - name: Update kubeconfig
          run : |
